services:
  - type: web
    name: cafe-seat-manager
    env: python
    buildCommand: ""
    startCommand: uvicorn IM_db_server:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000